### ISSUE TITLE
expose the inner fields of Game?

### ISSUE THREAD

**Issue by valyagolev** [carlostrub/backgammon#1]
Interested in using this crate to build some things. Is there any way to access the inner fields of Game? I want to be able to construct in-progress Games and look up their status. Perhaps simply making them all `pub` would a good enough idea?

**Comment by carlostrub** [comment]
Can you explain, what you mean by "in-progress" games? I am happy to expose some fields of Game, but I am a bit reluctant in exposing directly Cube or Board as they are not readily legible. For example, Cube is stored only as the exponential of 2. What would you need most?

**Comment by valyagolev** [comment]
for my purposes, all the information about games, including the cube value, should be readable and editable, not necessarily directly - methods would also work

**Comment by carlostrub** [comment]
ok, agreed. do you have any preferences for the board representation?

**Comment by valyagolev** [comment]
no, i will gladly convert from whatever you find more convenient and comprehensible, thank you!

**Comment by carlostrub** [comment]
ok, let me do this in the next couple of hours. I will update the version number then, please feel free to ping if this is not what you need.

**Comment by valyagolev** [comment]
there's no rush. thank you very much for this well-done crate

**Comment by carlostrub** [comment]
published version 0.6.0. please check out if this is what you need and if not, please raise new issue
